#!/bin/bash
## Use this script to create a new directory to be used as a new repository.
mkdir dirNname
cd dirName


## It initializes the repository and configures it.
git init
git config --global user.name username
git config --global user.email useremail
git config --global color.ui auto


## Add files to stage and commit.
git add .
git commit -m "comments"

## create repository branches.
git branch branchName

# It adds your remote repository and push.
git remote add pt https-ripository-link
git pull aliasName branchName
