#!/bin/bash
sudo hostname docker
sudo apt update -y 
sudo apt install docker.io -y
sudo usermod -aG docker ubuntu 
sudo su - ubuntu
=========================
Docker commands need admins right or
 sudo priviledges to run docker commands 
